[package]
name = "rust_tspath"
version = "1.0.0"
authors = ["José Quintana <https://git.io/joseluisq>"]

[dependencies]
log = "0.4.6"
simple_logger = "1.0.1"
glob = "0.2"
regex = "1"
lazy_static = "1.2.0"
json = "*"

[profile.release]
lto = true
